Fix URL for Google Cloud Storage backend.
This fixes an issue where Google Cloud Storage users encountered the
following exception:

System.Net.WebException: The remote server returned an error: (404) Not Found.

The refactoring in revision 18de687530 ("Updated Put and Createfolder
using WebApi") omitted the "/o" in the endpoint for object uploads.

This addresses issue #3328.