Fix restore search error in RestoreController (#4998)
* Fix restore search error in RestoreController.

TypeError: Cannot read Property 'Path' of undefined.
Add a break to for loop, thanks @tx0h (#4997).

* Remove empty '\' entries from restore picker.

The paths are split by dirsep, but directories end with it, which results in an empty part at the end.