Only create passphrase option if passphrase is provided.
This fixes an issue introduced in revision f7800e8a2bd where restores
from the UI would result in the following exception:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Empty passphrase not allowed
Parameter name: passphrase

This addresses issue #3542.