Skip build of DependencyFinder.
This fails with the following error:

Program.cs(42,36): error CS1503: Argument 1: cannot convert from 'string' to 'Mono.Cecil.AssemblyNameReference' [/home/runner/work/duplicati/duplicati/BuildTools/DependencyFinder/DependencyFinder.csproj]